baseURL = "https://rajkumaar.co.in"
title = "Online Home of Rajkumar S"
DefaultContentLanguage = "en"
theme = "hello-friend-ng"

[author]
name = "Rajkumar S"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
description = "Online home of Rajkumar S"
contentTypeName = "posts"
keywords = "homepage, portfolio, vCard, rajkumar, rajkumaar23"
homeSubtitle = "Software Engineer Intern | CodeChef"
defaultTheme = "dark"
themeColor = "#252627"

# Colors for favicons
[params.favicon.color]
mask = "#252627"
msapplication = "#252627"
theme = "#252627"

[params.logo]
logoText = "$ cd /home"
logoHomeLink = "/"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/rajkumaar23"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rajkumaar23"

[[params.social]]
name = "instagram"
url = "https://instagram.com/rajkumaar23"

[[params.social]]
name = "email"
url = "mailto:rajkumaar2304@icloud.com"

[[params.social]]
name = "telegram"
url = "https://t.me/rajkumaar23"

[menu]

[[menu.main]]
identifier = "about"
name = "about"
url = "about/"

[[menu.main]]
identifier = "resume"
name = "resume"
url = "resume/"

[[menu.main]]
name = "posts"
url = "/posts"
